### ISSUE TITLE
ESPHome Custom Component Deprecated - AC Dimmer Code No Longer Compiles

### ISSUE THREAD

**Issue by arzaman** [Makerfabs/Home-Assistant-AC-Dimmer#5]
# ESPHome Custom Component Deprecated - AC Dimmer Code No Longer Compiles

## 🐛 **Problem Description**

The current ESPHome configuration provided in the repository uses the deprecated `custom` component platform, which has been removed in recent ESPHome versions. This causes compilation failures when trying to use the AC Dimmer with modern ESPHome installations.

## 📋 **Error Details**

**Error Message:**
```
output.custom: [source /config/esphome/ac-dimmer.yaml:36] 
The "custom" component has been removed. Consider conversion to an external component. 
https://esphome.io/guides/contributing#a-note-about-custom-components.
```

**Current Code (Not Working):**
```yaml
output:
- platform: custom
  type: float
  lambda: |-
    auto my_dev_1 = new MyCustom_AT();
    App.register_component(my_dev_1);
    return {my_dev_1};
  
  outputs:
    id: my_dev_1
```

## 🔧 **Environment**

- **ESPHome Version:** 2024.11+ (and newer)
- **Hardware:** Makerfabs AC Dimmer for Home Assistant (ESP32 + STM32)
- **Home Assistant Version:** Latest
- **Issue Status:** Affects all new installations and updates

## 💡 **Why This Matters**

The Makerfabs AC Dimmer uses a unique architecture with:
- **ESP32**: Running ESPHome for Home Assistant integration
- **STM32**: Co-processor handling TRIAC control and zero-crossing detection
- **Serial Communication**: AT commands between ESP32 and STM32

This design **cannot** use the native ESPHome `ac_dimmer` component because it doesn't control GPIO pins directly - it sends serial commands to the STM32.

### **Option 1: Convert to External Component (Recommended)**
Convert the custom component to an external component format that works with modern ESPHome:

```yaml
external_components:
  - source: github://makerfabs/esphome-ac-dimmer-component
    components: [makerfabs_ac_dimmer]

output:
  - platform: makerfabs_ac_dimmer
    id: dimmer_output
    # Additional configuration options
```

### **Option 2: Update Documentation with Workaround**
Update the documentation to include the temporary fix using the community external component:

```yaml
external_components:
  - source: 
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [custom, custom_component]
```

### **Option 3: Provide Template-Based Alternative**
Create a template-based solution using UART communication:

```yaml
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200
  id: uart_stm32

output:
  - platform: template
    id: dimmer_output
    type: float
    write_action:
      - uart.write:
          id: uart_stm32
          data: !lambda |-
            // Convert float to AT command
            char buffer[50];
            int percentage = (int)(state * 100);
            sprintf(buffer, "AT+DIMMER=%d\r\n", percentage);
            return std::vector<uint8_t>(buffer, buffer + strlen(buffer));
```

## 📚 **Additional Information**

- **ESPHome Custom Component Removal:** https://esphome.io/guides/contributing#a-note-about-custom-components
- **External Components Guide:** https://esphome.io/components/external_components.html
- **Community Discussion:** https://community.home-assistant.io/t/i-made-a-esp32-ac-dimmer-with-support-esphome-homeassistant/610699

## 🎯 **Impact**

This issue affects:
- ✅ **New users** trying to set up the device
- ✅ **Existing users** updating ESPHome
- ✅ **Community adoption** of the product
- ✅ **Product documentation** accuracy

## 🙏 **Request**

Could the Makerfabs team please:

1. **Update the repository** with a modern ESPHome-compatible solution
2. **Create an external component** specifically for this hardware
3. **Update documentation** with current setup instructions
4. **Test compatibility** with latest ESPHome versions

This would ensure the AC Dimmer continues to work seamlessly with Home Assistant and ESPHome ecosystem updates.

## 🔗 **References**

- Current repository: https://github.com/Makerfabs/Home-Assistant-AC-Dimmer
- ESPHome documentation: https://esphome.io/
- Working temporary fix: https://github.com/robertklep/esphome-custom-component

Thank you for creating this innovative AC dimmer! Looking forward to a updated solution that works with modern ESPHome versions.
